<? if ($this->isPost != true) { ?>
    <div class="gradient page-title">
        <h1 class="inline"><?php echo $this->escape($this->title); ?></h1>
        <input name="name" class="right search-competition search-param" type="text"/>
    </div>
<? } ?>
<div class="competitions-action-index">
    <? if ($this->competitionsCount > 0) { ?>
        <div class="table-controls">
            <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination-control.phtml'); ?>
        </div>
        <div class="competitions-wrapper">
            <?= $this->partialLoop("competition/_competitionViewRow.phtml", $this->paginator); ?>
        </div>
        <div class="table-controls">
            <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination-control.phtml'); ?>
        </div>
    <? } else { ?>
        <p>Not found</p>
    <? } ?>
    <br/>
</div>