<!--<object width="305" height="270">
    <param value="http://www.youtube.com/v/v33zpuAk2Qw?fs=1&amp;hl=ru_RU" name="movie"/>
    <param value="true" name="allowFullScreen"/>
    <param value="always" name="allowscriptaccess"/>
    <param name='type' value='application/x-shockwave-flash'/>
    <param name='allowfullscreen' value='true'/>
    <param name='allowscriptaccess' value='always'/>
    <param name="wmode" value="transparent" />
    <embed width="305" height="270" allowfullscreen="true" allowscriptaccess="always"
           type="application/x-shockwave-flash"
           wmode="transparent"
           src="http://www.youtube.com/v/v33zpuAk2Qw?fs=1&amp;hl=ru_RU"/>
</object>
<iframe src="http://vkontakte.ru/video_ext.php?oid=62305047&id=159843884&hash=5d8a32654f5516a1&hd=1"
        width="305" height="270" frameborder="0">
</iframe>-->
<div>
    <h3>Кількість переглядів сайту: <span class="pink"><?= $this->numberOfPageRequests; ?></span></h3>
</div>

<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'contact')); ?>">
    <img width="100%" src="<?= $this->baseUrl() . '/img/zik.gif'; ?>" border=0 title="" alt="advertise here"/>
</a>
<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'contact')); ?>">
    <img width="100%" src="<?= $this->baseUrl() . '/img/joma.gif'; ?>" border=0 title="" alt="advertise here"/>
</a>
<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'contact')); ?>">
    <img width="100%" src="<?= $this->baseUrl() . '/img/stare-misto.gif'; ?>" border=0 title="" alt="advertise here"/>
</a>
