<div id="menu">
    <div class="page-width">
        <ul class="top">
            <?php echo $this->partialLoop('index/_menuItem.phtml', $this->menu) ?>
        </ul>
        <div class="right off">
            <input type="text" onfocus="if(this.value=='пошук...') this.value='';" onblur="if(this.value=='') this.value='пошук...';" value="пошук..." id="mod_search_searchword" style="" alt="Пошук" name="q"/>
        </div>
    </div>
</div>