<?
//
//$acl = new Zend_Acl();
//
//$acl->addRole(new Zend_Acl_Role('guest'))
//        ->addRole(new Zend_Acl_Role('member'))
//        ->addRole(new Zend_Acl_Role('admin'));
//
//$parents = array('guest', 'member', 'admin');
//$acl->addRole(new Zend_Acl_Role('someUser'), $parents);
//
//$acl->add(new Zend_Acl_Resource('someResource'));
//
//$acl->deny('guest', 'someResource');
//$acl->allow('member', 'someResource');
//
//echo $acl->isAllowed('someUser', 'someResource') ? 'разрешен' : 'запрещен';
?>
<div class="wd-element">
    <img src="images/1.jpg" alt="Some Image" />
    <div class="wd-info">
        <div class="wd-info-title">
            <h2>Название</h2>
        </div>
        <div class="wd-info-desc">
            <p>Описание</p>
        </div>
    </div>
</div>