<h1 class="gradient">An error occured</h1>
<h2><?= $this->message;?></h2>

<div class="error-description black off">
    <img class="bug-image" class="left" width="100" height="100" src="<?=$this->baseUrl() . '/img/bugs/bug_1.jpg'; ?>" alt=""/>
<? if ('development' == getenv('APPLICATION_ENV')) { ?>
    <h3> Exception information: </h3>
    <p>
        <b>Message:</b> <?= $this->exception->getMessage(); ?>
    </p>
    <br class="clear"/>
    <h3>Stack Trace</h3>
    <pre><?=$this->exception->getTraceAsString(); ?> </pre>

    <h3>Request Parameters</h3>
    <pre><? var_dump($this->request->getParams()); ?> </pre>
    <pre><?Zend_Debug::dump($this->exceptionsDetails, 'exceptionsDetails'); ?></pre>

    <? } else {

} ?>

</div>
<a href="javascript:void(0)" id="error-details">Detail</a>
