<?
$session = Model_Session::getSession();
?>
<div class="identity-wrapper">
    <?php if ($this->identity == null) { ?>
        <a class="login strong" href='javascript:void(0)'>Sign In</a> | 
        <a class="register strong" href='/registration/'>Register</a>
    <?php } else { ?>
        <span>Hi <?php echo $this->identity->first_name; ?></span>
        <? if ($session->storage->user->isAdmin()) { ?>
            <div class="instruments-wrapper ">
                <a class="instruments strong green" href='javascript:void(0)'>Instruments</a>
                <div class="submenu off">
                    <a class=" pink" href="">My Profile</a><br/>
                    <a class=" pink" href="">Add Partner Event</a><br/>
                    <a class=" pink" href="/">Chapter Reports</a><br/>
                </div>
            </div>
        <? } ?>
        <a class="logout strong green" href='/user/logout'>Sign Out</a>
    <?php } ?>
</div>
<?//?>
