<h1 class="gradient"><?php echo $this->escape($this->title); ?></h1>
<a href="<?=$this->baseUrl(); ?>/competition/manage">Змагання</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/club/manage">Клуби</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/player/manage">Гравці</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/user/list">Користувачі</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/role/manage">Ролі</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/test">Тест</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/competition/responsibility/">Зв'язки змагань з командами</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/club/responsibility/">Зв'язки команд із змаганнями</a>
<br/>
<a href="<?=$this->baseUrl(); ?>/club/associate/2">Зв'язки конкретної команди</a>
